encoding: utf-8
name: Krisha Mehta
url: https://krishamehta.github.io/
author:
  name: Krisha Mehta
  email: krisha1204@gmail.com
description: Computer science student who likes to learn and read.
permalink: /posts/:title/
include: ['_pages']
