encoding: utf-8
name: Krisha Mehta
url: https://krisha-mehta.github.io/
author:
  name: Krisha Mehta
  email: krisha@uchicago.edu
description: PhD student in Computer Science at the University of Chicago, studying data visualization and uncertainty reasoning.
permalink: /posts/:title/
include: ['_pages']
